# Generated by Django 5.2.6 on 2025-09-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_draft_user_id_alter_like_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='poll_id',
            new_name='draft_id',
        ),
    ]
