# Generated by Django 5.2.6 on 2025-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_draft_creation_date_like_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
