# Generated by Django 5.2.6 on 2025-12-20 20:21

import django.db.models.deletion
import django_countries.fields
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('gender', models.CharField(blank=True, default='Prefer not to say', max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
