# Generated by Django 5.2.6 on 2025-12-24 01:59

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
