# Generated by Django 5.2.6 on 2026-01-05 21:01

import django.utils.timezone
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_characteristics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='age',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
