# Generated by Django 5.2.6 on 2026-01-05 22:47

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_characteristics_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 22, 47, 42, 363233, tzinfo=datetime.timezone.utc)),
        ),
    ]
