# Generated by Django 5.2.6 on 2026-01-06 15:39

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_characteristics_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 15, 39, 16, 247845, tzinfo=datetime.timezone.utc)),
        ),
    ]
