# Generated by Django 5.2.6 on 2025-12-27 21:47

import django.db.models.deletion
import django_countries.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_remove_option_votes_alter_like_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('gender', models.CharField(blank=True, default='Prefer not to say', max_length=32, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
            ],
        ),
    ]
