# Generated by Django 5.2.6 on 2025-12-29 02:06

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_vote_user_alter_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='gender',
        ),
        migrations.AddField(
            model_name='vote',
            name='characteristics_snapshot',
            field=models.JSONField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
