# Generated by Django 5.2.6 on 2025-12-31 04:30

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_vote_age_remove_vote_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
