# Generated by Django 5.2.6 on 2025-12-31 04:30

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_like_id_alter_option_id_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_period',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
