# Generated by Django 5.2.6 on 2026-01-05 21:01

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_vote_period_alter_like_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
